import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  java: [
    {
      type: 'category',
      label: '基本知识',
      link: {
        type: 'generated-index',
      },
      items: [
        'java/JAVA',
        'java/JAVA-JDK-Version',
        'java/JAVA-JVM',
        'java/JAVA-Maven',
        'java/JAVA-Maven-Dependent',
        'java/JAVA-Thread',
        'java/JAVA-Servlet',
        'java/JAVA-Error-Record',
        'java/JAVA-MybatisPlus',
      ],
    },
    {
      type: 'category',
      label: 'Spring',
      link: {
        type: 'generated-index',
      },
      items: [
        'java/JAVA-SpringBoot-Version',
        'java/JAVA-SpringBoot-Stack',
        'java/JAVA-SpringCloud-Stack',
      ],
    },
    {
      type: 'category',
      label: '知识算法',
      link: {
        type: 'generated-index',
      },
      items: [
        'java/JAVA-Algorithm',
        'java/JAVA-Design-Pattern',
        'java/JAVA-Knowledge-Question',
        'java/JAVA-Code-Generation',
        'java/JAVA-Data-Structure',
        'java/JAVA-Encryption',
        'java/JAVA-SQL-Interceptor',
        'java/JAVA-OAuth2-SourceCode',
      ],
    },
    'java/JAVA-MQ',
    {
      type: 'category',
      label: '技术工具',
      link: {
        type: 'generated-index',
      },
      items: [
        'java/JAVA-PDF',
        'java/JAVA-Hutool',
        'java/JAVA-WebSocket',
      ],
    },
  ],
  web: [{ type: 'autogenerated', dirName: 'web' }],
  c: [{ type: 'autogenerated', dirName: 'c' }],
  linux: [{ type: 'autogenerated', dirName: 'linux' }],
  sql: [{ type: 'autogenerated', dirName: 'sql' }],
  python: [{ type: 'autogenerated', dirName: 'python' }],
  tool: [{ type: 'autogenerated', dirName: 'tool' }],
  project: [{ type: 'autogenerated', dirName: 'project' }],
  other: [{ type: 'autogenerated', dirName: 'other' }],
  knowledge: [{ type: 'autogenerated', dirName: 'knowledge' }],

  // But you can create a sidebar manually
  example: [
    'example/EXAMPLE-Video',
  ],
}

export default sidebars;
